config/routes.rb
Rails.application.routes.draw do

  devise_for :seguridad_usuarios, controllers: {
    sessions: 'seguridad_usuarios/sessions',
    registrations: 'seguridad_usuarios/registrations'
  }
  
  resources :categories
  resources :entradas
  resources :seguridad_usuarios
  
  get 'ver_entrada/index'
  get 'ver_entrada/index/:id' => 'ver_entrada#index'

  get 'practica_form_tag/index'
  get 'practica_render/index'
  get 'practica_render/index_dos'
  get 'practica_ruby/index'
  get 'practica_variables/index'

  
  get 'home/index'
  get 'home/parametro'

  get 'ayuda/index'
  get 'ayuda/editar'

  root 'home#index'

  get 'home/parametro/:id' => 'home#parametro'
  get 'ayuda/pagina/:id' => 'ayuda#pagina'

end

app/models/entrada.rb
class Entrada < ActiveRecord::Base
  belongs_to :seguridad_usuario
  belongs_to :category
  has_many :comentarios

  validates :fecha, presence: { message: 'Requerido' }
  validates :titulo, presence: { message: 'Requerido' }
  validates :category_id, presence: { message: 'Requerido' }
  validates :seguridad_usuario_id, presence: { message: 'Requerido' }

  has_paper_trail

  scope :count_comentarios, -> {
  	joins(:comentarios, :seguridad_usuario, :category)
    .select('entradas.id, entradas.fecha, entradas.titulo,
            entradas.texto, entradas.visitas, entradas.publicado,
            count(comentarios.id) as cantidad_comentarios,
            seguridad_usuarios.username as username,
            categories.nombre as categoria')
    .group('entradas.id, entradas.fecha, entradas.titulo,
           entradas.texto, seguridad_usuarios.username,
           categories.nombre')
  }

end

app/controllers/entradas_controller.rb
class EntradasController < PrivatesController
  layout 'administracion'
  before_action :set_entrada, only: [:show, :edit, :update, :destroy]

  # GET /entradas
  # GET /entradas.json
  def index
    @entradas = Entrada.all
  end

  # GET /entradas/1
  # GET /entradas/1.json
  def show
  end

  # GET /entradas/new
  def new
    @entrada = Entrada.new
  end

  # GET /entradas/1/edit
  def edit
  end

  # POST /entradas
  # POST /entradas.json
  def create
    @entrada = Entrada.new(entrada_params)
    @entrada.seguridad_usuario_id = current_seguridad_usuario.id

    respond_to do |format|
      if @entrada.save
        format.html { redirect_to @entrada, notice: 'Entrada fue creada satisfactoriamente.' }
        format.json { render :show, status: :created, location: @entrada }
      else
        format.html { render :new }
        format.json { render json: @entrada.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entradas/1
  # PATCH/PUT /entradas/1.json
  def update
    respond_to do |format|
      if @entrada.update(entrada_params)
        format.html { redirect_to @entrada, notice: 'Entrada fue actualizada satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @entrada }
      else
        format.html { render :edit }
        format.json { render json: @entrada.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entradas/1
  # DELETE /entradas/1.json
  def destroy
    @entrada.destroy
    respond_to do |format|
      format.html { redirect_to entradas_url, notice: 'Entrada fue eliminada satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entrada
      @entrada = Entrada.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entrada_params
      params.require(:entrada).permit(:fecha, :titulo, :texto, :visitas, :publicado, :seguridad_usuario_id, :category_id)
    end
end

app/helpers/entradas_helper.rb
module EntradasHelper
end

app/views/entradas/_form.html.erb
<%= form_for(@entrada) do |f| %>
  <% if @entrada.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entrada.errors.count, "error") %> prohibited this entrada from being saved:</h2>

      <ul>
      <% @entrada.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :fecha, class: 'control-label' %><br>
    <%= f.date_select :fecha, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :titulo, class: 'control-label' %><br>
    <%= f.text_field :titulo, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :texto, class: 'control-label' %><br>
    <%= f.text_area :texto, class: 'form-control', rows: 6 %>
  </div>
  <div class="form-group">
    <%= f.label :visitas, class: 'control-label' %><br>
    <%= f.number_field :visitas, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :publicado, class: 'control-label' %><br>
    <%= f.check_box :publicado %>
  </div>
  <div class="form-group">
    <%= f.label :category_id, class: 'control-label' %><br>
    <%= f.select :category_id, Category.all.collect { |u| [ u.nombre, u.id ] },
                 { include_blank: false }, { class: 'form-control' } %>
  </div>
  <div class="actions">
    <%= f.submit 'Guardar', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/entradas/edit.html.erb
<h1>Editando Entrada</h1>

<%= render 'form' %>

<%= link_to 'Ver', @entrada %> |
<%= link_to 'Atras', entradas_path %>

app/views/entradas/index.html.erb
<h1>Lista De Entradas</h1>

<table class="table">
  <thead>
    <tr>
      <th>Fecha</th>
      <th>Titulo</th>
      <th>Publicado</th>
      <th>Usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entradas.each do |entrada| %>
      <tr>
        <td><%= entrada.fecha %></td>
        <td><%= entrada.titulo.truncate(80) %></td>
        <td><%= entrada.publicado ? 'Si' : 'No' %></td>
        <td><%= entrada.seguridad_usuario.username %></td>
        <td>
          <p data-placement="top" data-toggle="tooltip" title="Ver">
            <%= link_to entrada, class: 'btn btn-primary btn-xs' do %>
              <span class="glyphicon glyphicon-eye-open"></span>
            <% end %>
          </p>
        </td>
        <td>
          <p data-placement="top" data-toggle="tooltip" title="Editar">
            <%= link_to edit_entrada_path(entrada), class: 'btn btn-primary btn-xs' do %>
              <span class="glyphicon glyphicon-pencil"></span>
            <% end %>
          </p>
        </td>
        <td>
          <p data-placement="top" data-toggle="tooltip" title="Eliminar">
            <%= link_to entrada, class: 'btn btn-primary btn-xs', method: :delete, data: { confirm: 'Esta seguro?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
            <% end %>
          </p>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Entrada', new_entrada_path %>

app/views/entradas/new.html.erb
<h1>New Entrada</h1>

<%= render 'form' %>

<%= link_to 'Atras', entradas_path %>

app/views/entradas/show.html.erb
<% if notice.present? %>
  <%= content_tag :div, notice, class: 'alert alert-success' %>
<% end %>
<h1>Entrada: <%= @entrada.id %></h1>
<table class="table">
  <tbody>
    <tr>
      <td>Fecha</td>
      <td><%= @entrada.fecha %></td>
    </tr>
    <tr>
      <td>Titulo</td>
      <td><%= @entrada.titulo %></td>
    </tr>
    <tr>
      <td>Texto</td>
      <td><%= @entrada.texto %></td>
    </tr>
    <tr>
      <td>Visitas</td>
      <td><%= @entrada.visitas %></td>
    </tr>
    <tr>
      <td>Publicado</td>
      <td><%= @entrada.publicado ? 'Si' : 'No' %></td>
    </tr>
    <tr>
      <td>Usuario</td>
      <td><%= @entrada.seguridad_usuario.username %></td>
    </tr>
    <tr>
      <td>Categoria</td>
      <td><%= @entrada.category.nombre %></td>
    </tr>
  </tbody>
</table>

<%= link_to 'Editar', edit_entrada_path(@entrada) %> |
<%= link_to 'Atras', entradas_path %>