config/routes.rb
Rails.application.routes.draw do

  devise_for :seguridad_usuarios, controllers: {
    sessions: 'seguridad_usuarios/sessions',
    registrations: 'seguridad_usuarios/registrations'
  }
  
  resources :categories
  resources :entradas
  resources :seguridad_usuarios
  
  get 'ver_entrada/index'
  get 'ver_entrada/index/:id' => 'ver_entrada#index'

  get 'practica_form_tag/index'
  get 'practica_render/index'
  get 'practica_render/index_dos'
  get 'practica_ruby/index'
  get 'practica_variables/index'

  
  get 'home/index'
  get 'home/parametro'

  get 'ayuda/index'
  get 'ayuda/editar'

  root 'home#index'

  get 'home/parametro/:id' => 'home#parametro'
  get 'ayuda/pagina/:id' => 'ayuda#pagina'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :entradas

	validates :nombre, presence: { message: 'Requerido'}
	has_paper_trail
end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
  belongs_to :entrada
  belongs_to :seguridad_usuario
end

app/models/entrada.rb
class Entrada < ActiveRecord::Base
  belongs_to :seguridad_usuario
  belongs_to :category
  has_many :comentarios

  validates :fecha, presence: { message: 'Requerido' }
  validates :titulo, presence: { message: 'Requerido' }
  validates :category_id, presence: { message: 'Requerido' }
  validates :seguridad_usuario_id, presence: { message: 'Requerido' }

  has_paper_trail

  scope :count_comentarios, -> {
  	joins(:comentarios, :seguridad_usuario, :category)
    .select('entradas.id, entradas.fecha, entradas.titulo,
            entradas.texto, entradas.visitas, entradas.publicado,
            count(comentarios.id) as cantidad_comentarios,
            seguridad_usuarios.username as username,
            categories.nombre as categoria')
    .group('entradas.id, entradas.fecha, entradas.titulo,
           entradas.texto, seguridad_usuarios.username,
           categories.nombre')
  }

end

app/models/seguridad_usuario.rb
class SeguridadUsuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	strip_attributes
	has_paper_trail
	# has_paper_trail ignore: [:nombres]
	# has_paper_trail only: [:username]
	# has_paper_trail on: [:update, :destroy]

	validates :username, uniqueness: { message: 'Este usuario ya existe'},
		                   presence: { message: 'Requerido'}, 
		                   length: {maximum: 20, too_long: 'Demasiados caracteres'},
		                   format: {with: /\A[a-z]{0,20}\z/, message: 'Solo letras'} 
	
	validates :nombres, presence: { message: 'Requerido'}, 
		                  length: {maximum: 250, too_long: 'Demasiados caracteres'},
		                  format: {with: /\A[a-zA-Z]{0,20}\z/, message: 'Solo letras'} 
	
	validates :apellidos, presence: { message: 'Requerido'}, 
		                    length: {maximum: 20, too_long: 'Demasiados caracteres'},
		                    format: {with: /\A[a-zA-Z]{0,20}\z/, message: 'Solo letras'} 	                     	                     

end

app/controllers/ayuda_controller.rb
class AyudaController < ApplicationController
	layout 'ayuda', except: [:editar]
  
  def index
  end

  def editar
  end

  def pagina
  	pagina_id = params[:id]
  	render text: "Estamos en la pagina ##{pagina_id} de la ayuda"
  end
end

app/controllers/categories_controller.rb
class CategoriesController < PrivatesController
  layout 'administracion'
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Categoria fue creada satisfactoriamente' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Categoria fue actualizada satisfactoriamente' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Categoria fue eliminada satisfactoriamente' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:nombre)
    end
end

app/controllers/entradas_controller.rb
class EntradasController < PrivatesController
  layout 'administracion'
  before_action :set_entrada, only: [:show, :edit, :update, :destroy]

  # GET /entradas
  # GET /entradas.json
  def index
    @entradas = Entrada.all
  end

  # GET /entradas/1
  # GET /entradas/1.json
  def show
  end

  # GET /entradas/new
  def new
    @entrada = Entrada.new
  end

  # GET /entradas/1/edit
  def edit
  end

  # POST /entradas
  # POST /entradas.json
  def create
    @entrada = Entrada.new(entrada_params)
    @entrada.seguridad_usuario_id = current_seguridad_usuario.id

    respond_to do |format|
      if @entrada.save
        format.html { redirect_to @entrada, notice: 'Entrada fue creada satisfactoriamente.' }
        format.json { render :show, status: :created, location: @entrada }
      else
        format.html { render :new }
        format.json { render json: @entrada.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entradas/1
  # PATCH/PUT /entradas/1.json
  def update
    respond_to do |format|
      if @entrada.update(entrada_params)
        format.html { redirect_to @entrada, notice: 'Entrada fue actualizada satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @entrada }
      else
        format.html { render :edit }
        format.json { render json: @entrada.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entradas/1
  # DELETE /entradas/1.json
  def destroy
    @entrada.destroy
    respond_to do |format|
      format.html { redirect_to entradas_url, notice: 'Entrada fue eliminada satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entrada
      @entrada = Entrada.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entrada_params
      params.require(:entrada).permit(:fecha, :titulo, :texto, :visitas, :publicado, :seguridad_usuario_id, :category_id)
    end
end

app/controllers/home_controller.rb
# controlador para el home
class HomeController < ApplicationController
  def index
  	@entradas = Entrada.count_comentarios
  end

  def parametro
  	parameters = params[:id].humanize
  	render text: 'El parametro es: ' + parameters
  end
end

app/controllers/privates_controller.rb
class PrivatesController < ApplicationController
  before_action :authenticate_seguridad_usuario!

  def user_for_paper_trail
  	if seguridad_usuario_signed?
  		current_seguridad_usuario.id
  	else
  		'Public User'
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ayuda_helper.rb
module AyudaHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/entradas_helper.rb
module EntradasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/practica_form_tag_helper.rb
module PracticaFormTagHelper
end

app/helpers/practica_render_helper.rb
module PracticaRenderHelper
end

app/helpers/practica_ruby_helper.rb
module PracticaRubyHelper
end

app/helpers/practica_variables_helper.rb
module PracticaVariablesHelper
end

app/helpers/seguridad_usuarios_helper.rb
module SeguridadUsuariosHelper
end

app/helpers/ver_entrada_helper.rb
module VerEntradaHelper
end

app/views/layouts/administracion.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Curso Rails</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Entradas', entradas_path %></li>
            <li><%= link_to 'Usuarios', seguridad_usuarios_path %></li>
            <li><%= link_to 'Categorias', categories_path %></li>
            <li><%= link_to 'Ayuda', ayuda_index_path %></li>
            <% if seguridad_usuario_signed_in? %>
              <li><%= link_to current_seguridad_usuario.username, seguridad_usuario_path(current_seguridad_usuario) %></li>
              <li><%= link_to 'salir', destroy_seguridad_usuario_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to 'Iniciar Sesión', new_seguridad_usuario_session_path %></li>
              <li><%= link_to 'Registrarse', new_seguridad_usuario_registration_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container-fluid" style="margin-top: 60px; margin-bottom: 40px;">
      <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-10">
          <%= yield %>
        </div>
        <div class="col-sm-1"></div>
      </div>
    </div>

    <%= render 'layouts/shared/footer' %>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= render 'layouts/shared/header' %>

    <div class="container">
      <div class="row">
        <div class="col-sm-8 blog-main">
          <%= yield %>
        </div><!-- /.blog-main -->
        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h4>Acerca</h4>
            <p>Aplicación desarrollada con el framework de desarrollo de
            aplicaciones web Raals</p>
          </div>
          <div class="sidebar-module">
            <h4>Categorias</h4>
            <ol class="list-unstyled">
              <% Category.all.each do |categoria| %>
                <li><%= link_to categoria.nombre, '#' %></li>
              <% end %>
            </ol>
          </div>
        </div><!-- /.blog-sidebar -->
      </div><!-- /.row -->
    </div><!-- /.container -->

    <%= render 'layouts/shared/footer' %>

  </body>
</html>

app/views/layouts/ayuda.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/shared/header' %>

	<%= yield %>

	<%= render 'layouts/shared/footer' %>
</body>
</html>

app/views/layouts/shared/_footer.html.erb
<footer class="blog-footer">
  <p>Blog template built for <a href="http://getbootstrap.com">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/layouts/shared/_header.html.erb
<div class="blog-masthead">
  <div class="container">
    <nav class="blog-nav">
      <%= link_to 'Inicio', home_index_url, { class: 'blog-nav-item' } %>
      <%= link_to 'Ayuda', ayuda_index_path, { class: 'blog-nav-item' } %>
      <%= link_to 'Administración', entradas_path, { class: 'blog-nav-item' } %>
      <ul class="nav navbar-nav navbar-right">
        <% if seguridad_usuario_signed_in? %>
          <li><%= link_to current_seguridad_usuario.username, seguridad_usuario_path(current_seguridad_usuario) %></li>
          <li><%= link_to 'salir', destroy_seguridad_usuario_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Iniciar Sesión', new_seguridad_usuario_session_path %></li>
          <li><%= link_to 'Registrarse', new_seguridad_usuario_registration_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</div>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: (name=='notice' ? 'alert alert-success' : 'alert alert-danger' ) %>
<% end %>